go mod init name
go mod tidy 
go mod verify // check go.sum hash
go list all /go list -m all
go list -m -version github.com/gorilla/mux
go mod why github.com/gorilla/mux
go mod graph 
go mod edit -go 1.18 // change go version
go mod edit -module name
go mod vendor // download all packege in your code override some module
go run mod=vendor main.go